### ISSUE TITLE
HM logo shown on auth screen

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cli#8]
Current when you authenticate, I see

![](https://joehoyle-captured.s3-eu-west-1.amazonaws.com/Screen-Shot-2023-02-23-11-23-41.01-Yq70y0m0CY6WYxUrb2yvKyAtzrlkdgihPuMhuZd7qz2KC7OCo8CKSSgbmdsEAn7DWwojQXDNKx7kLwPvkrKGoEGDox7J9p6nbq09.png)

This should be changed to Altis I believe. 

### Acceptance criteria

* [ ] Logo and name on auth screen are changed to Altis

**Comment by kovshenin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-cli/8?planning-poker) with Zenhub @ferschubert-hm @jerico @mikelittle @wisyhambolu

**Comment by wisyhambolu** [comment]
humanmade/product-dev#1347 has been created to have a stylesheet that can be used in this issue.

**Comment by wisyhambolu** [comment]
humanmade/product-dev#1347 has been created to have a stylesheet that can be used in this issue.

**Comment by rmccue** [comment]
Ended up fixing both of these at once by switching to a Tailwind CSS file
